### ISSUE TITLE
Calibration Pass 2 does not ask for the best value from pass 1.

### ISSUE THREAD

**Issue by Grayzone233** [CrealityOfficial/CrealityPrint#113]
When using the calibration tools, once pass 1 is complete and you pick the best sample then go to Pass2 ver 4 used to ask what was the best sample from pass 1. Ver 5 does not ask it just creates some more samples.

**Comment by Wowo14b** [comment]
Yeah I have the same problem

**Comment by Grayzone233** [comment]
Well they changed the process so you don't need to enter the pass 1 number. See.
https://github.com/SoftFever/OrcaSlicer/wiki/Calibration
