### ISSUE TITLE
App icon has white background on MacOS

### ISSUE THREAD

**Issue by rxfxt** [CrealityOfficial/CrealityPrint#119]
The app icon for Creality Print 5.0.2 has a white background in Launchpad and Dock on MacOS:

![image](https://github.com/CrealityOfficial/CrealityPrint/assets/76214963/91fcd6f7-040f-4e5d-bcde-514198078688)

When app is open, the icon is displayed correctly with no white background:

![image](https://github.com/CrealityOfficial/CrealityPrint/assets/76214963/b12c9a6b-3c0d-4c54-b843-348216039a8b)

**Comment by Ababuy78** [comment]
And there is no native arm version.
